export const FETCH_DAILY_INSPENTION_REPORT_CARD = 'FETCH/DAILY/INSPENTION/REPORT/CARD'

export const FETCH_DAILY_INSPENTION_REPORT_CARD_SUCCESS = 'FETCH/DAILY/INSPENTION/REPORT/CARD/SUCCESS'

export const FETCH_DAILY_INSPENTION_REPORT_CARD_FAIL = 'FETCH/DAILY/INSPENTION/REPORT/CARD/FAIL'

