export const FETCH_DAILY_INSPENTION_REPORT_CARD = 'FETCH/DAILY/INSPENTION/REPORT/CARD'

export const FETCH_DAILY_INSPENTION_REPORT_CARD_SUCCESS = 'FETCH/DAILY/INSPENTION/REPORT/CARD/SUCCESS'

export const FETCH_DAILY_INSPENTION_REPORT_CARD_FAIL = 'FETCH/DAILY/INSPENTION/REPORT/CARD/FAIL'

export const GET_INSPECTION_PEOPLE = 'GET/INSPECTION/PEOPLE'

export const GET_INSPECTION_PEOPLE_SUCCESS = 'GET/INSPECTION/PEOPLE/SUCCESS'

export const GET_INSPECTION_PEOPLE_FAIL = 'GET/INSPECTION/PEOPLE/FAIL'

export const FETCH_DUTY_PEOPLE = 'FETCH/DUTY/PEOPLE'

export const FETCH_INSPENTION_DATE = 'FETCH/INSPENTION/DATE'

