export const SELECT_EMERGENCY_PLAN_ONE = '0';
export const SELECT_EMERGENCY_PLAN_TWO = '1';
export const SELECT_EMERGENCY_PLAN_THREE = '2';

export const SELECT_EMERGENCY_PLAN_LEVEL_MAP = {
  [SELECT_EMERGENCY_PLAN_ONE]: '1',
  [SELECT_EMERGENCY_PLAN_TWO]: '2',
  [SELECT_EMERGENCY_PLAN_THREE]: '3',
};

export const SELECT_EMERGENCY_PLAN_LEVEL = Object.keys(SELECT_EMERGENCY_PLAN_LEVEL_MAP).map(cur => ({
  id: cur,
  name: SELECT_EMERGENCY_PLAN_LEVEL_MAP[cur],
}));