export const BMAP_DRAWING_POLYGON =window.BMAP_DRAWING_POLYGON;
export const BMAP_DRAWING_RECTANGLE=window.BMAP_DRAWING_RECTANGLE;
export const BMAP_DRAWING_CIRCLE= window.BMAP_DRAWING_CIRCLE;
export const BMAP_DRAWING_POLYLINE= window.BMAP_DRAWING_POLYLINE;
